// Generated by gencpp from file dynamixel_current_2port/Select_MotionResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_SELECT_MOTIONRESPONSE_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_SELECT_MOTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_current_2port
{
template <class ContainerAllocator>
struct Select_MotionResponse_
{
  typedef Select_MotionResponse_<ContainerAllocator> Type;

  Select_MotionResponse_()
    : Select_Motion(0)  {
    }
  Select_MotionResponse_(const ContainerAllocator& _alloc)
    : Select_Motion(0)  {
  (void)_alloc;
    }



   typedef int8_t _Select_Motion_type;
  _Select_Motion_type Select_Motion;





  typedef boost::shared_ptr< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Select_MotionResponse_

typedef ::dynamixel_current_2port::Select_MotionResponse_<std::allocator<void> > Select_MotionResponse;

typedef boost::shared_ptr< ::dynamixel_current_2port::Select_MotionResponse > Select_MotionResponsePtr;
typedef boost::shared_ptr< ::dynamixel_current_2port::Select_MotionResponse const> Select_MotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator1> & lhs, const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Select_Motion == rhs.Select_Motion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator1> & lhs, const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_current_2port

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5aaa1cdf85b33c7430af49dec6f787c6";
  }

  static const char* value(const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5aaa1cdf85b33c74ULL;
  static const uint64_t static_value2 = 0x30af49dec6f787c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_current_2port/Select_MotionResponse";
  }

  static const char* value(const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 Select_Motion\n"
;
  }

  static const char* value(const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Select_Motion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Select_MotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_current_2port::Select_MotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "Select_Motion: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Select_Motion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_SELECT_MOTIONRESPONSE_H
