// Generated by gencpp from file dynamixel_current_2port/Turn_Angle.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_TURN_ANGLE_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_TURN_ANGLE_H

#include <ros/service_traits.h>


#include <dynamixel_current_2port/Turn_AngleRequest.h>
#include <dynamixel_current_2port/Turn_AngleResponse.h>


namespace dynamixel_current_2port
{

struct Turn_Angle
{

typedef Turn_AngleRequest Request;
typedef Turn_AngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Turn_Angle
} // namespace dynamixel_current_2port


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_current_2port::Turn_Angle > {
  static const char* value()
  {
    return "6bcc5ac74e5ed33763d25bed29ca1508";
  }

  static const char* value(const ::dynamixel_current_2port::Turn_Angle&) { return value(); }
};

template<>
struct DataType< ::dynamixel_current_2port::Turn_Angle > {
  static const char* value()
  {
    return "dynamixel_current_2port/Turn_Angle";
  }

  static const char* value(const ::dynamixel_current_2port::Turn_Angle&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_current_2port::Turn_AngleRequest> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::Turn_Angle >
template<>
struct MD5Sum< ::dynamixel_current_2port::Turn_AngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::Turn_Angle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::Turn_AngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::Turn_AngleRequest> should match
// service_traits::DataType< ::dynamixel_current_2port::Turn_Angle >
template<>
struct DataType< ::dynamixel_current_2port::Turn_AngleRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::Turn_Angle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::Turn_AngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_current_2port::Turn_AngleResponse> should match
// service_traits::MD5Sum< ::dynamixel_current_2port::Turn_Angle >
template<>
struct MD5Sum< ::dynamixel_current_2port::Turn_AngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_current_2port::Turn_Angle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::Turn_AngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_current_2port::Turn_AngleResponse> should match
// service_traits::DataType< ::dynamixel_current_2port::Turn_Angle >
template<>
struct DataType< ::dynamixel_current_2port::Turn_AngleResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_current_2port::Turn_Angle >::value();
  }
  static const char* value(const ::dynamixel_current_2port::Turn_AngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_TURN_ANGLE_H
