// Generated by gencpp from file dynamixel_current_2port/Turn_AngleRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_CURRENT_2PORT_MESSAGE_TURN_ANGLEREQUEST_H
#define DYNAMIXEL_CURRENT_2PORT_MESSAGE_TURN_ANGLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_current_2port
{
template <class ContainerAllocator>
struct Turn_AngleRequest_
{
  typedef Turn_AngleRequest_<ContainerAllocator> Type;

  Turn_AngleRequest_()
    : finish(false)  {
    }
  Turn_AngleRequest_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Turn_AngleRequest_

typedef ::dynamixel_current_2port::Turn_AngleRequest_<std::allocator<void> > Turn_AngleRequest;

typedef boost::shared_ptr< ::dynamixel_current_2port::Turn_AngleRequest > Turn_AngleRequestPtr;
typedef boost::shared_ptr< ::dynamixel_current_2port::Turn_AngleRequest const> Turn_AngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator1> & lhs, const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator1> & lhs, const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_current_2port

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_current_2port/Turn_AngleRequest";
  }

  static const char* value(const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finish\n"
;
  }

  static const char* value(const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Turn_AngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_current_2port::Turn_AngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_CURRENT_2PORT_MESSAGE_TURN_ANGLEREQUEST_H
