(cl:defpackage dynamixel_current_2port-srv
  (:use )
  (:export
   "SELECT_MOTION"
   "<SELECT_MOTION-REQUEST>"
   "SELECT_MOTION-REQUEST"
   "<SELECT_MOTION-RESPONSE>"
   "SELECT_MOTION-RESPONSE"
   "TURN_ANGLE"
   "<TURN_ANGLE-REQUEST>"
   "TURN_ANGLE-REQUEST"
   "<TURN_ANGLE-RESPONSE>"
   "TURN_ANGLE-RESPONSE"
  ))

